### ISSUE TITLE
Looking for contributors 

### ISSUE THREAD

**Issue by GazzaHazza** [GhostGroup/grid-styled#16]
Hi,

Just wondering if you are looking for contributors at all?

**Comment by bringking** [comment]
@GazzaHazza Thanks for reaching out! We have a good set of people already going to contribute, however we are always open to PR's. If you make enough PRs, we would be happy to add you as a contributor

**Comment by timurista** [comment]
Looks like your question was answered Gazza, we are closing this then

**Comment by GazzaHazza** [comment]
Yeah thank you. Sorry should of closed this.
