### ISSUE TITLE
Wrap prop on Flex component

### ISSUE THREAD

**Issue by GazzaHazza** [GhostGroup/grid-styled#17]
First off, thanks for picking this repo up and maintaining it.

Just moved to from `grid-styled` to this repo, im running into a issue where the `wrap` prop on the `Flex`.  I refactored from `wrap` to `flexWrap` and it is not adding `flex-wrap` attribute in the css.

Just curious if you knew why?

**Comment by bringking** [comment]
@GazzaHazza Not sure, it is working in the examples in the repo. Let me dig in again and make sure we didn't miss anything

**Comment by bringking** [comment]
@GazzaHazza hmm yea something is weird. I will work on a fix

**Comment by GazzaHazza** [comment]
@bringking Thanks for that!

**Comment by bringking** [comment]
@GazzaHazza got it fixed here - https://github.com/GhostGroup/grid-styled/pull/18. Once merged, I will do a patch release

**Comment by GazzaHazza** [comment]
@bringking, Great work. Thanks for the quick fix! 👍

**Comment by bringking** [comment]
@GazzaHazza npm updated with 3.0.1 - https://www.npmjs.com/package/@ghostgroup/grid-styled

**Comment by GazzaHazza** [comment]
@bringking  🙌  - Thanks
