### ISSUE TITLE
<Box /> Component does not support `is` propType

### ISSUE THREAD

**Issue by solidflows** [GhostGroup/grid-styled#22]
Hello,
Thanks for taking over this project.
When changing over to this, I noticed when I pass the `is` propType to the Box component, it no longer works. It just outputs the attribute without transforming the element underneath. Looking at the src/ I couldn't find any mention of the propType even though the Readme has it documented. Is this propType still supported?

Usage:
`<Box is="section">I'm a section tag</Box>`

Intended Result:
`<section>I'm a section tag</section>`

Actual Result:
`<div is="section">I'm a section tag</div>`

**Comment by bringking** [comment]
@solidflows let me take a look, we removed the flakey implementation of the base component with a raw styled div. This is probably causing the error. Sorry about that! I believe I can implement a workaround, however long term, keeping it closer to styled-components best practices and just extending box is how we use it.

```js
const SectionBox = Box.withComponent('section')
```

**Comment by solidflows** [comment]
I'm not sure if this helps - the way I'm using this component is as a base component that I can pass multiple children to and those children might be inside a div, ul, section, etc. so I would need to transform how the box renders to keep the children tags consistent.

A sample of what it might be for list items:
`<ul>
<Flex {...props}>
{React.children.map(props.children, (grandChild, i) => (
<Box is={grandChild.type} {...grandChild.props}>{grandChild.children}</Box>
))}
</Flex>
</ul>`

**Comment by bringking** [comment]
@solidflows, yeah that makes sense, I will fix this

**Comment by bringking** [comment]
Just to serve as a reminder, this regression went out and the tests didnt' catch it. the tests in this codebase need to be refreshed

**Comment by bringking** [comment]
@solidflows @boxman0617 3.0.2 is published and fixes the `is` prop!

**Comment by boxman0617** [comment]
Yay!!!! Thanks for this man!
