### ISSUE TITLE
Update Grid to use a range of display settings

### ISSUE THREAD

**Issue by timurista** [GhostGroup/grid-styled#6]
## Context
The current Grid component is using display: 'inline-block'. 
Can we refactor to use `display: grid | inline-grid | subgrid;`?

The browser support now is very positive
https://caniuse.com/#feat=css-grid

## Notes
This issue was pulled from the original repo https://github.com/jxnblk/grid-styled/issues/61 by @stevemao

**Comment by bringking** [comment]
Some work on this here -> https://github.com/GhostGroup/grid-styled/pull/27. I think once this gets merged we can close this.
