### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by timurista** [GhostGroup/grid-styled#7]
## Context
The latest version version on npm is 1.0.0-beta.1 which depends on styled-components v1, which is causing some issues. Could you publish the new src?

originally published here: https://github.com/jxnblk/grid-styled/issues/60

**Comment by bringking** [comment]
@timurista I think the original is up to 2.x on NPM here - https://www.npmjs.com/package/grid-styled. Based on the changes I have made, when we release to NPM (we can do this tomorrow), it will be a major version bump to 3.0 based on the API changes in this PR - https://github.com/GhostGroup/grid-styled/pull/2

**Comment by timurista** [comment]
cool, when we publish to 3.0 I can close this then

**Comment by bringking** [comment]
Done! https://www.npmjs.com/package/@ghostgroup/grid-styled

**Comment by timurista** [comment]
nice! 👍 closing this then
