### ISSUE TITLE
Limit NPM Publish size

### ISSUE THREAD

**Issue by bringking** [GhostGroup/grid-styled#9]
Currently all the files are published to NPM. We need to use the `files` block to limit to the bare minimum.

**Comment by timurista** [comment]
you can also run this package as part of your tests to enforce a strict bundle size: `npm install bundlesize` that's what preact does anyways. https://www.npmjs.com/package/bundlesize

**Comment by timurista** [comment]
@bringking yo I can add this to the test flow what do you think would be a reasonable size to limit?

**Comment by bringking** [comment]
@timurista yeah that could be cool. I would say that would be a different issue/enhancement. This issue is specific to how much data we ship up to NPM. In reality, we just need to ship the `dist` folder and the package.json

**Comment by timurista** [comment]
sounds good, just need to update package json sounds like

**Comment by GazzaHazza** [comment]
I am happy to do this. I cloned this repo and done the change just getting access denied when trying to push the branch?

**Comment by timurista** [comment]
@GazzaHazza make sure to fork an do a PR

**Comment by GazzaHazza** [comment]
@timurista - ahhh ok, ill do that

**Comment by timurista** [comment]
fix has been merged
